[2024-06-01T18:28:12.466+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T18:28:12.485+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid19_project_dag.get_data manual__2024-06-01T18:28:11.315332+00:00 [queued]>
[2024-06-01T18:28:12.610+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid19_project_dag.get_data manual__2024-06-01T18:28:11.315332+00:00 [queued]>
[2024-06-01T18:28:12.610+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-01T18:28:12.622+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_data> on 2024-06-01 18:28:11.315332+00:00
[2024-06-01T18:28:12.627+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=405) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-01T18:28:12.628+0000] {standard_task_runner.py:63} INFO - Started process 407 to run task
[2024-06-01T18:28:12.628+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'covid19_project_dag', 'get_data', 'manual__2024-06-01T18:28:11.315332+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/covid19_project_dag.py', '--cfg-path', '/tmp/tmp7srwjyne']
[2024-06-01T18:28:12.630+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask get_data
[2024-06-01T18:28:12.666+0000] {task_command.py:426} INFO - Running <TaskInstance: covid19_project_dag.get_data manual__2024-06-01T18:28:11.315332+00:00 [running]> on host b18befda89c1
[2024-06-01T18:28:12.739+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kelvin' AIRFLOW_CTX_DAG_ID='covid19_project_dag' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T18:28:11.315332+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T18:28:11.315332+00:00'
[2024-06-01T18:28:12.741+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T18:28:14.021+0000] {logging_mixin.py:188} INFO - [[{'date': '2020-01-25', 'state': 'Malaysia', 'cases_new': 4, 'cases_active': 4, 'cases_import': 4, 'cases_cluster': 0, 'cases_recovered': 0}], [{'date': '2020-01-25', 'state': 'Malaysia', 'cases_fvax': 0, 'cases_pvax': 0, 'cases_boost': 0, 'cases_unvax': 4}], [{'date': '2020-01-25', 'state': 'Malaysia', 'cases_80': 0, 'cases_0_4': 0, 'cases_5_11': 0, 'cases_12_17': 0, 'cases_18_29': 0, 'cases_30_39': 0, 'cases_40_49': 1, 'cases_50_59': 0, 'cases_60_69': 0, 'cases_70_79': 0, 'cases_adult': 1, 'cases_child': 0, 'cases_elderly': 0, 'cases_adolescent': 0}]]
[2024-06-01T18:28:14.022+0000] {python.py:237} INFO - Done. Returned value was: [[{'date': '2020-01-25', 'state': 'Malaysia', 'cases_new': 4, 'cases_active': 4, 'cases_import': 4, 'cases_cluster': 0, 'cases_recovered': 0}], [{'date': '2020-01-25', 'state': 'Malaysia', 'cases_fvax': 0, 'cases_pvax': 0, 'cases_boost': 0, 'cases_unvax': 4}], [{'date': '2020-01-25', 'state': 'Malaysia', 'cases_80': 0, 'cases_0_4': 0, 'cases_5_11': 0, 'cases_12_17': 0, 'cases_18_29': 0, 'cases_30_39': 0, 'cases_40_49': 1, 'cases_50_59': 0, 'cases_60_69': 0, 'cases_70_79': 0, 'cases_adult': 1, 'cases_child': 0, 'cases_elderly': 0, 'cases_adolescent': 0}]]
[2024-06-01T18:28:14.022+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T18:28:14.040+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=covid19_project_dag, task_id=get_data, run_id=manual__2024-06-01T18:28:11.315332+00:00, execution_date=20240601T182811, start_date=20240601T182812, end_date=20240601T182814
[2024-06-01T18:28:14.086+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-01T18:28:14.103+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-01T18:28:14.104+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
